create table citizen (
	village_id INT,
	citizen_id INT  ,
	aadhar VARCHAR(50) PRIMARY KEY,
	gender VARCHAR(50),
	name VARCHAR(6),
	email VARCHAR(50),
	image VARCHAR(157),
	household_id INT REFERENCES household(household_id),
	dob DATE,
	education_qualification VARCHAR(50)
);

insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,1, '0657256277', 'Male', 'Rajesh', 'lbeedham0@hatena.ne.jp', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 11, '8/23/1966','Illiterate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,2, '9334432217', 'Male', 'Rahul', 'acasarili1@theglobeandmail.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 26, '7/21/1959','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,3, '1738976637', 'Female', 'Sunita', 'smadgett2@hostgator.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 37, '6/9/2007','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,4, '9843151038', 'Female', 'Meera', 'adavidzon3@springer.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 37, '10/2/1959','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (8,5, '0705376672', 'Male', 'Rahul', 'aitzik4@skyrock.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 37, '9/10/1990','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,6, '0615153267', 'Male', 'Sanjay', 'gsheryne5@opera.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 55, '456/4/1997','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,7, '1867725169', 'Female', 'Priya', 'wstrewthers6@free.fr', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 50, '12/31/1994','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,8, '2796036790', 'Male', 'Vikram', 'kgoacher7@youku.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 47, '9/17/1966','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,9, '1030364362', 'Female', 'Anjali', 'lmackaile8@ezinearticles.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 8, '2/19/1962','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,10, '2164310470', 'Male', 'Rajesh', 'hcosbee9@chronoengine.com', 'https://static.vecteezy.com/system/resources/thumbnails/053/735/280/small/a-man-smiles-in-front-of-a-crowd-photo.jpeg', 29, '5/16/1971','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,11, '0435572547', 'Male', 'Amit', 'eblazya@freewebs.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 21, '1/17/1975','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,12, '8221886300', 'Female', 'Anjali', 'kpedderb@hubpages.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 42, '1/24/1962','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,13, '5798369242', 'Male', 'Rahul', 'vmacalisterc@github.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 13, '235/10/1984','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,14, '5927429572', 'Female', 'Meera', 'mspeedd@vk.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 20, '11/13/2003','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,15, '6668155669', 'Male', 'Rajesh', 'jmatselle@eventbrite.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 37, '7/16/1994','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,16, '8324017682', 'Female', 'Priya', 'iwebbenf@parallels.com', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 43, '2/4/1995','Illiterate',);
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,17, '9337902877', 'Female', 'Pooja', 'eroweng@vk.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 8, '4/17/1978','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,18, '1730602002', 'Male', 'Rajesh', 'bwhistanh@plala.or.jp', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 16, '5/29/2001','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,19, '7368462036', 'Male', 'Sanjay', 'espinii@sina.com.cn', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 14, '11/11/1982','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,20, '2253563439', 'Female', 'Pooja', 'mmillinsj@boston.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 8, '2/26/1988','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,21, '0955487307', 'Male', 'Rajesh', 'vwillowsk@guardian.co.uk', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 11, '6/17/2003','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,22, '8865937912', 'Female', 'Priya', 'craesidel@dyndns.org', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 11, '10/10/1961','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,23, '8887933154', 'Male', 'Rajesh', 'lebbettsm@netlog.com', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 50, '12/18/2001','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,24, '7896711230', 'Male', 'Vikram', 'jjowersn@dailymotion.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 23, '2/20/1952','Illiterate',);
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,25, '8014071964', 'Male', 'Vikram', 'mszanthoo@house.gov', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 21, '8/26/1982','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,26, '7725423117', 'Female', 'Sunita', 'jsurgisonp@miitbeian.gov.cn', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 49, '12/8/1956','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,27, '1219757764', 'Male', 'Rahul', 'gdyteq@amazon.de', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 77, '434/7/2000','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,28, '8395867948', 'Male', 'Rahul', 'afraczekr@fda.gov', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 19, '9/27/2000','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,29, '9179368883', 'Male', 'Vikram', 'sferrolis@google.pl', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 9, '2212/14/1964','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,30, '4389678981', 'Female', 'Priya', 'deaglestonet@sohu.com', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 26, '7/18/1962','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,31, '4210540358', 'Male', 'Amit', 'jcarlyleu@is.gd', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 26, '11/20/1988','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,32, '2133322914', 'Male', 'Rajesh', 'pharcusv@umich.edu', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 23, '9/27/1967','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,33, '8803510117', 'Female', 'Meera', 'cinglefieldw@squidoo.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 16, '16/30/1983','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,34, '7827572200', 'Male', 'Amit', 'kgerriessenx@amazon.de', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 36, '11/5/1993','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,35, '9000743656', 'Female', 'Sunita', 'hvassely@usnews.com', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 41, '9/26/1979','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,36, '0956802141', 'Male', 'Sanjay', 'ahazeupz@live.com', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 82, '264/25/1961','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,37, '3976823082', 'Male', 'Rajesh', 'lbeckhurst10@amazon.de', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 27, '8/4/1951','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,38, '8711409096', 'Male', 'Rajesh', 'kbarnet11@nationalgeographic.com', 'https://static.vecteezy.com/system/resources/thumbnails/053/735/280/small/a-man-smiles-in-front-of-a-crowd-photo.jpeg', 26, '232/28/1984','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,39, '9831941209', 'Male', 'Rahul', 'elampart12@g.co', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 61, '174/21/1988','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,40, '5367729711', 'Male', 'Amit', 'kcreed13@sohu.com', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 21, '271/7/1989','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,41, '4546926561', 'Female', 'Priya', 'phorsley14@xrea.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 12, '10/7/1998','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (8,42, '0984844058', 'Male', 'Amit', 'ncopley15@ebay.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 4, '6/4/1982','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (8,43, '1499946546', 'Female', 'Pooja', 'sdwight16@reuters.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 41, '6/12/2003','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,44, '3670401474', 'Male', 'Rajesh', 'hayshford17@goodreads.com', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 41, '11/20/2008','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,45, '1243964863', 'Male', 'Rahul', 'osoutheran18@home.pl', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 48, '2/29/1992','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,46, '2351926285', 'Female', 'Anjali', 'sadamik19@bbb.org', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 45, '10/10/1987','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,47, '7379198998', 'Male', 'Amit', 'cchipchase1a@ca.gov', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 25, '6/11/1984','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,48, '1669565408', 'Male', 'Rahul', 'mtowns1b@go.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 27, '472/17/1977','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,49, '3570447855', 'Male', 'Vikram', 'kbaudin1c@cargocollective.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 93, '188/27/1992','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,50, '9647116241', 'Female', 'Priya', 'msaer1d@nature.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 26, '4/25/1965','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,51, '0949191248', 'Female', 'Priya', 'vgateland1e@scientificamerican.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 36, '1/26/1989','Illiterate',);
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,52, '2112793950', 'Female', 'Anjali', 'bmacnab1f@princeton.edu', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 76, '173/1/1959','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (8,53, '1433581051', 'Male', 'Amit', 'bwindsor1g@github.io', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 11, '5/19/1957','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,54, '1071371274', 'Female', 'Sunita', 'gnealand1h@shop-pro.jp', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 47, '12/30/1999','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,55, '9287402159', 'Male', 'Sanjay', 'dcasado1i@cam.ac.uk', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 33, '11/11/1986','Illiterate',);
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,56, '1643511572', 'Male', 'Amit', 'wbernlin1j@flickr.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 37, '5/21/1960','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,57, '3752566175', 'Female', 'Meera', 'nghilks1k@addthis.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 97, '359/10/1967','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,58, '9804563770', 'Male', 'Vikram', 'hgorrick1l@mit.edu', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 44, '3/5/1972','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,59, '0210809310', 'Female', 'Pooja', 'crodders1m@washingtonpost.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 39, '5/3/1978','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,60, '9994209884', 'Female', 'Meera', 'kminchin1n@goodreads.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 7, '12/13/2000','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,61, '8243581146', 'Female', 'Sunita', 'ckennett1o@comsenz.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 7, '81/19/1974','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,62, '3808843055', 'Male', 'Rajesh', 'qlyttle1p@bbb.org', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 46, '4/25/1988','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,63, '4095921633', 'Male', 'Rajesh', 'rjorg1q@4shared.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 46, '5/19/1957','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,64, '8227627412', 'Male', 'Vikram', 'awestphalen1r@buzzfeed.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 37, '126/5/1954','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,65, '1330848659', 'Female', 'Priya', 'gsargison1s@tripadvisor.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 31, '11/20/2006','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,66, '3500823963', 'Male', 'Rajesh', 'abeckerleg1t@pinterest.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 31, '2/18/1999','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (8,67, '9151086867', 'Male', 'Rajesh', 'alydall1u@vimeo.com', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 9, '2/25/1999','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,68, '5053768617', 'Female', 'Meera', 'emcgriele1v@examiner.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 33, '8/7/1974','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,69, '7241639502', 'Female', 'Sunita', 'agallo1w@pinterest.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 25, '10/1/1982','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,70, '7634094307', 'Male', 'Rahul', 'gunwins1x@state.gov', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 20, '3/13/1967','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,71, '6823754060', 'Male', 'Rajesh', 'kstoile1y@walmart.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 38, '9/15/2003','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,72, '1511433345', 'Female', 'Priya', 'tstrethill1z@census.gov', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 45, '4/9/1955','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,73, '2479256081', 'Female', 'Priya', 'mbrockwell20@prweb.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 28, '9/26/1972','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,74, '0564382833', 'Male', 'Sanjay', 'hmanderson21@unesco.org', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 1, '10/11/1976','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,75, '0425684105', 'Female', 'Meera', 'olampens22@angelfire.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 54, '454/1/1996','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,76, '9935105849', 'Female', 'Sunita', 'jjerrand23@g.co', 'https://img.freepik.com/premium-photo/girl-resting-village-near-hay-portrait-woman-sun-rustic-style-portrait-sexy-brunette-hayloft-perfect-makeup_91497-5952.jpg?w=740', 32, '11/1/1956','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,77, '6574134323', 'Female', 'Priya', 'srevens24@tripadvisor.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 13, '2/23/1994','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,78, '7992278046', 'Male', 'Rajesh', 'mvardon25@oakley.com', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 16, '1/7/1980','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,79, '7200570001', 'Female', 'Anjali', 'hgaskin26@arizona.edu', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 32, '1/26/1996','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,80, '4086287048', 'Female', 'Pooja', 'grodgers27@bloomberg.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 46, '10/10/1969','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (7,81, '7036118741', 'Male', 'Vikram', 'dgirdlestone28@bbb.org', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 1, '5/11/2008','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,82, '4949785540', 'Male', 'Vikram', 'dback29@mlb.com', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 34, '11/26/1966','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,83, '8589791688', 'Male', 'Rajesh', 'mwhicher2a@hhs.gov', 'https://static.vecteezy.com/system/resources/thumbnails/053/735/280/small/a-man-smiles-in-front-of-a-crowd-photo.jpeg', 19, '3/2/1994','Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,84, '8035197525', 'Female', 'Anjali', 'hjahnel2b@weebly.com', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 44, '5/14/1955','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,85, '3402690454', 'Male', 'Vikram', 'aabsolem2c@wordpress.org', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 15, '487/5/2006','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (4,86, '6275351292', 'Female', 'Sunita', 'cmottershaw2d@unicef.org', 'https://static.vecteezy.com/system/resources/thumb…ra-with-confidence-generated-by-ai-free-photo.jpg', 38, '9/9/1968','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,87, '1137411155', 'Female', 'Pooja', 'tsoppett2e@unc.edu', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 25, '6/23/1952','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,88, '0840183062', 'Male', 'Amit', 'ebullcock2f@wufoo.com', 'https://static.vecteezy.com/system/resources/thumb…indian-boy-smiling-on-black-background-photo.jpeg', 44, '10/21/1951','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (5,89, '9682778913', 'Male', 'Sanjay', 'jwerlock2g@opensource.org', 'https://static.vecteezy.com/system/resources/previews/034/359/781/non_2x/a-man-standing-in-front-of-a-village-ai-generated-free-photo.jpg', 34, '6/3/2008','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (1,90, '8573554193', 'Female', 'Pooja', 'afaithfull2h@lulu.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 35, '12/31/1974','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,91, '5925171454', 'Male', 'Amit', 'hizard2i@china.com.cn', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 2, '3910/26/1992','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,92, '1549048686', 'Male', 'Rajesh', 'dbreddy2j@dot.gov', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 45, '1/30/1950','10th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,93, '9448625413', 'Male', 'Rahul', 'hrankcom2k@netvibes.com', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 89, '495/15/1966','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,94, '0494813997', 'Male', 'Sanjay', 'rtrengrouse2l@google.es', 'https://static.vecteezy.com/system/resources/previews/055/699/917/non_2x/portrait-of-a-bearded-indian-farmer-wearing-a-traditional-turban-and-shawl-photo.jpg', 14, '6/6/1993','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (2,95, '1132060850', 'Female', 'Anjali', 'jliggett2m@networksolutions.com', 'https://img.freepik.com/free-photo/portrait-adorable-indian-girl_23-2150913178.jpg', 41, '7/4/1980','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,96, '9308770569', 'Male', 'Sanjay', 'mlabrow2n@cdbaby.com', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 4, '12/15/2000','Secondary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (9,97, '2415502944', 'Male', 'Rahul', 'mfosdyke2o@omniture.com', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 13, '9/2/1975','12th');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (10,98, '5834968791', 'Male', 'Rajesh', 'nwild2p@google.es', 'https://static.vecteezy.com/system/resources/previews/040/980/468/large_2x/ai-generated-portrait-of-an-old-hindu-man-neural-network-ai-generated-photo.jpg', 8, '3/14/1964','Primary');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (6,99, '8714072858', 'Male', 'Vikram', 'lbreward2q@slashdot.org', 'https://static.vecteezy.com/system/resources/thumbnails/053/735/280/small/a-man-smiles-in-front-of-a-crowd-photo.jpeg', 42, '153/7/1954','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (3,100, '5721407115', 'Male', 'Vikram', 'pschwieso2r@google.co.uk', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 55, '164/7/1999','Post-Graduate');
insert into citizen (village_id,citizen_id, aadhar, gender, name, email, image, household_id, dob,education_qualification ) values (101, '5721407115', 'Male', 'Ajitesh', 'pschwieso2r@google.co.uk', 'https://thumbs.dreamstime.com/b/portrait-old-hindu…-man-white-turban-maharashtra-india-309830981.jpg', 55, '4/7/1999','Post-Graduate');

